name: Chocolatine

on:
  push:
    branches:
      - main

jobs:
  run-make-command:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source repository
        uses: actions/checkout@v2
        with:
          repository: EpitechPromo2027/B-CPE-110-BDX-1-1-BSQ-tom.bouisset
          token: ${{ secrets.PAT }}

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Run make Command
        run: |
          make